# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parse_pdf": "00_api.ipynb",
         "logger": "00_api.ipynb"}

modules = ["api.py"]

doc_url = "https://UCREL.github.io/science_parse_py_api/"

git_url = "https://github.com/UCREL/science_parse_py_api/tree/main/"

def custom_doc_links(name): return None
